

import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class ANGGOTA extends javax.swing.JFrame {
private Statement st;
private Connection Con = new koneksi().connect();
private ResultSet Rs;
private String Tanggal="";
private String Sql="";
private String host;
public String kodeanggota,namaanggota,nomorinduksekolah,jeniskelamin,Tanggal_lahir,tempatlahir,alamat,No_hp;

/**
     * Creates new form ANGGOTA
     */
    public ANGGOTA() {
        initComponents();
        this.setTitle("Perpustakaan MTS SALFIYAH SAFI'IYAH");
        TampilAnggota("SELECT*FROM anggota");
        kosongkan();    
    }
     public Connection koneksi() throws SQLException{
         Connection khusus = null;
         
        try {
            Class.forName("com.mysql.jdbc.Driver");    //Jika Tidak Terjadi Error
            khusus = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpustakaan","root","");
            return khusus;
        } catch (ClassNotFoundException ex) {
          return null;
        }catch (SQLException ex){
            return null;
        }
     }
     private void TampilAnggota(String Sql){
        DefaultTableModel  grid=new DefaultTableModel();
        grid.addColumn("No");
        grid.addColumn("Kode Anggota");
        grid.addColumn("Nama Anggota");
        grid.addColumn("Nomor_induk_sekolah");
        grid.addColumn("Jenis Kelamin");
        grid.addColumn("Tanggal_lahir");
        grid.addColumn("Tempat Lahir");
        grid.addColumn("Alamat");
        grid.addColumn("No_hp");
        try {
            int i=1;
            st=Con.createStatement();
            Rs=st.executeQuery("SELECT*FROM anggota");
            while (Rs.next()){
                grid.addRow(new Object[]{
                    (""+i++),Rs.getString(1),
                    Rs.getString(2),
                    Rs.getString(3),
                    Rs.getString(4),
                    Rs.getString(5),
                    Rs.getString(6),
                    Rs.getString(7),
                    Rs.getString(8)
            });
               TANGGOTA.setModel(grid);
               TANGGOTA.enable(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Gagal Tampil: "+e);
        }
     }
      private void kosongkan (){
         TXTKODEANGGOTA.setText("");
         TXTNAMAANGGOTA.setText("");
         TXTNIS.setText("");
         CBJENISKELAMIN.addItem("Select");
         JTANGGAL.setDate(null);
         TXTTEMPATLAHIR.setText("");
         TXTALAMAT.setText("");
         TXTNOHP.setText("");
         TXTKODEANGGOTA.requestFocus();
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXTKODEANGGOTA = new javax.swing.JTextField();
        TXTNAMAANGGOTA = new javax.swing.JTextField();
        TXTTEMPATLAHIR = new javax.swing.JTextField();
        CBJENISKELAMIN = new javax.swing.JComboBox<>();
        TXTALAMAT = new javax.swing.JTextField();
        TXTNOHP = new javax.swing.JTextField();
        BTNSIMPAN = new javax.swing.JButton();
        BTNEDIT = new javax.swing.JButton();
        BTNHAPUS = new javax.swing.JButton();
        BTNBATAL = new javax.swing.JButton();
        BTNKELUAR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TANGGOTA = new javax.swing.JTable();
        JTANGGAL = new com.toedter.calendar.JDateChooser();
        btncetak = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TXTNIS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/anggota1.png"))); // NOI18N
        jLabel1.setText(" ANGGOTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("KODE ANGGOTA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("NAMA ANGGOTA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("JENIS KELAMIN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("TANGGAL LAHIR");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("TEMPAT LAHIR");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("ALAMAT");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("NO HP");

        TXTKODEANGGOTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTKODEANGGOTAActionPerformed(evt);
            }
        });
        TXTKODEANGGOTA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTKODEANGGOTAKeyPressed(evt);
            }
        });

        CBJENISKELAMIN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CBJENISKELAMIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Laki - Laki", "Perempuan" }));

        BTNSIMPAN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNSIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button simpan.png"))); // NOI18N
        BTNSIMPAN.setText("SIMPAN");
        BTNSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSIMPANActionPerformed(evt);
            }
        });

        BTNEDIT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNEDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button Edit.png"))); // NOI18N
        BTNEDIT.setText("EDIT");
        BTNEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITActionPerformed(evt);
            }
        });

        BTNHAPUS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNHAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Hapus_1.png"))); // NOI18N
        BTNHAPUS.setText("HAPUS");
        BTNHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHAPUSActionPerformed(evt);
            }
        });

        BTNBATAL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNBATAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button batal.png"))); // NOI18N
        BTNBATAL.setText("BATAL");
        BTNBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBATALActionPerformed(evt);
            }
        });

        BTNKELUAR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNKELUAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button Keluar.png"))); // NOI18N
        BTNKELUAR.setText("KELUAR");
        BTNKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKELUARActionPerformed(evt);
            }
        });

        TANGGOTA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Anggota", "Nama Anggota", "Nomor Induk Sekolah", "Jenis Kelamin", "Tanggal Lahir", "Tempat Lahir", "Alamat", "No Hp"
            }
        ));
        jScrollPane2.setViewportView(TANGGOTA);

        JTANGGAL.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JTANGGALPropertyChange(evt);
            }
        });

        btncetak.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btncetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button Cetak.png"))); // NOI18N
        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("NOMOR INDUK SEKOLAH");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("KODE PENCARIAN");

        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });

        bcari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBJENISKELAMIN, 0, 129, Short.MAX_VALUE)
                            .addComponent(TXTNIS)
                            .addComponent(TXTNAMAANGGOTA)
                            .addComponent(TXTKODEANGGOTA))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTTEMPATLAHIR)
                                    .addComponent(JTANGGAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(82, 82, 82)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTALAMAT)
                                    .addComponent(TXTNOHP))))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BTNSIMPAN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNEDIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNBATAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNHAPUS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(BTNKELUAR))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel11)
                .addGap(35, 35, 35)
                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(bcari)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JTANGGAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTTEMPATLAHIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTKODEANGGOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTNAMAANGGOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(TXTALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CBJENISKELAMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTNOHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNSIMPAN)
                    .addComponent(BTNEDIT)
                    .addComponent(BTNHAPUS)
                    .addComponent(BTNBATAL)
                    .addComponent(BTNKELUAR)
                    .addComponent(btncetak))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSIMPANActionPerformed
        // TODO add your handling code here:
        kodeanggota=TXTKODEANGGOTA.getText();
        namaanggota=TXTNAMAANGGOTA.getText();
        nomorinduksekolah=TXTNIS.getText();
        jeniskelamin=CBJENISKELAMIN.getItemAt(CBJENISKELAMIN.getSelectedIndex());
        tempatlahir=TXTTEMPATLAHIR.getText();
        alamat=TXTALAMAT.getText();
        No_hp=TXTNOHP.getText();
        try {
            Sql="INSERT INTO anggota"
                    + "(Kode_anggota,Nama_anggota,Nomor_induk_sekolah,Jenis_kelamin,Tanggal_lahir,Tempat_lahir,Alamat,No_hp)"
                    + "VALUES('"+ kodeanggota+"',"
                    + "'"+namaanggota+"',"
                    + "'"+nomorinduksekolah+"',"
                    + "'"+jeniskelamin+"',"
                    + "'"+Tanggal+"',"
                    + "'"+tempatlahir+"',"
                    + "'"+alamat+"',"
                    + "'"+No_hp+"')";
            st=Con.createStatement();
            st.execute(Sql);
            kosongkan();
            TampilAnggota("SELECT*FROM anggota");
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            BTNSIMPAN.enable(true);             
        } catch (Exception e) {
           JOptionPane.showConfirmDialog(null,"Data Tidak Tersimpan\n"+e.getMessage());
        }                                       
                                           
    }//GEN-LAST:event_BTNSIMPANActionPerformed

    private void JTANGGALPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JTANGGALPropertyChange
        // TODO add your handling code here:
            if(JTANGGAL.getDate()!=null){
            SimpleDateFormat format =new SimpleDateFormat ("yyyy-MM-dd");
            Tanggal=format.format(JTANGGAL.getDate());
        }
    }//GEN-LAST:event_JTANGGALPropertyChange

    private void BTNEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITActionPerformed
        // TODO add your handling code here:
        kodeanggota=TXTKODEANGGOTA.getText();
        namaanggota=TXTNAMAANGGOTA.getText();
        nomorinduksekolah=TXTNIS.getText();
        jeniskelamin=CBJENISKELAMIN.getItemAt(CBJENISKELAMIN.getSelectedIndex());
        tempatlahir=TXTTEMPATLAHIR.getText();
        alamat=TXTALAMAT.getText();
        No_hp=TXTNOHP.getText();
        try { Sql="UPDATE anggota SET Nama_anggota='"+namaanggota+"',"
                + "Nomor_induk_sekolah='"+nomorinduksekolah+"',"
                + "Jenis_kelamin='"+jeniskelamin+"',"
                + "Tanggal_lahir='"+Tanggal+"',"
                + "Tempat_lahir='"+tempatlahir+"',"
                + "Alamat='"+alamat+"',"
                + "No_hp='"+No_hp+"'"
                + "WHERE Kode_anggota='"+kodeanggota+"'";
         st=Con.createStatement();
            st.execute(Sql);
            kosongkan();
            TampilAnggota("SELECT*FROM anggota");
            JOptionPane.showMessageDialog(null, "Data Berhasl Di Edit");
            BTNSIMPAN.show();      
        } catch (Exception e) {
             JOptionPane.showConfirmDialog(null,"Data Tidak Di Perbaharui\n"+e.getMessage());
        }                                
    }//GEN-LAST:event_BTNEDITActionPerformed

    private void BTNHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHAPUSActionPerformed
        // TODO add your handling code here:
        kodeanggota=TXTKODEANGGOTA.getText();
        try { Sql="DELETE FROM anggota "
                + "WHERE Kode_anggota='" +kodeanggota+ "'";
         st=Con.createStatement();
            st.execute(Sql);
            kosongkan();
            TampilAnggota("SELECT*FROM anggota");
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
            BTNSIMPAN.show();            
        } catch (Exception e) {
             JOptionPane.showConfirmDialog(null,"Data Tidak Di Hapus\n"+e.getMessage());
        }       
    }//GEN-LAST:event_BTNHAPUSActionPerformed

    private void BTNBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBATALActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_BTNBATALActionPerformed

    private void TXTKODEANGGOTAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTKODEANGGOTAKeyPressed
        // TODO add your handling code here:
                 kodeanggota=TXTKODEANGGOTA.getText();
        int A = evt.getKeyCode();
        if (A==10){
            try {
                Sql="SELECT * FROM anggota WHERE Kode_anggota='"+kodeanggota+"'";
                st=Con.createStatement();
                Rs=st.executeQuery(Sql);
                while(Rs.next()){
            TXTNAMAANGGOTA.setText(Rs.getString(2));
            TXTNIS.setText(Rs.getString((3)));
            CBJENISKELAMIN.setSelectedItem(Rs.getString(4));
            JTANGGAL.setDate(Rs.getDate(5));
            TXTTEMPATLAHIR.setText(Rs.getString(6));
            TXTALAMAT.setText(Rs.getString(7));
            TXTNOHP.setText(Rs.getString(8));
            BTNSIMPAN.enable(false);
            BTNEDIT.enable(true);
            BTNHAPUS.enable(true);
                }
            } catch (Exception e) {
                    JOptionPane.showConfirmDialog(null, "Data Tidak Ditemukan\n"+e.getMessage());
                    TXTNAMAANGGOTA.requestFocus();
            }
        }
    }//GEN-LAST:event_TXTKODEANGGOTAKeyPressed

    private void TXTKODEANGGOTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTKODEANGGOTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTKODEANGGOTAActionPerformed

    private void BTNKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKELUARActionPerformed
        // TODO add your handling code here:
       new MenuUtama().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BTNKELUARActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        try{
            String file = "src/lapanggota.jasper";
            JasperPrint jp = JasperFillManager.fillReport(file, null, koneksi());
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
        }catch (Exception e) {
        }
    }//GEN-LAST:event_btncetakActionPerformed

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        // TODO add your handling code here:
        try {
            Sql="select * from anggota where Kode_anggota='"+tcari.getText()+"'";
            st=Con.createStatement();
            Rs=st.executeQuery(Sql);
            while(Rs.next()){    
                TXTKODEANGGOTA.setText(Rs.getString("Kode_anggota"));
                TXTNAMAANGGOTA.setText(Rs.getString("Nama_anggota"));
                TXTNIS.setText(Rs.getString("Nomor_induk_sekolah"));
                CBJENISKELAMIN.setSelectedItem(Rs.getString("Jenis_kelamin"));
                JTANGGAL.setDate(Rs.getDate("Tanggal_lahir"));
                TXTTEMPATLAHIR.setText(Rs.getString("Tempat_lahir"));
                TXTALAMAT.setText(Rs.getString("Alamat"));
                TXTNOHP.setText(Rs.getString("No_hp"));
            }           
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ANGGOTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ANGGOTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ANGGOTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ANGGOTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ANGGOTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBATAL;
    private javax.swing.JButton BTNEDIT;
    private javax.swing.JButton BTNHAPUS;
    private javax.swing.JButton BTNKELUAR;
    private javax.swing.JButton BTNSIMPAN;
    private javax.swing.JComboBox<String> CBJENISKELAMIN;
    private com.toedter.calendar.JDateChooser JTANGGAL;
    private javax.swing.JTable TANGGOTA;
    private javax.swing.JTextField TXTALAMAT;
    private javax.swing.JTextField TXTKODEANGGOTA;
    private javax.swing.JTextField TXTNAMAANGGOTA;
    private javax.swing.JTextField TXTNIS;
    private javax.swing.JTextField TXTNOHP;
    private javax.swing.JTextField TXTTEMPATLAHIR;
    private javax.swing.JButton bcari;
    private javax.swing.JButton btncetak;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tcari;
    // End of variables declaration//GEN-END:variables

}
