
import java.io.File;
import java.io.InputStream;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class login extends javax.swing.JFrame {    
private Connection conn= new koneksi().connect();
protected String[] 
    FILE_PATH = {
        "/lapanggota",
        "/lapbuku",
        "/lapkartu",
        "/lappeminjaman",
        "/lappengembalian"};
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setTitle("Perpustakaan MTS SALAFIYAH SYAFI'IYYAH");
        initiateResourceFile();
    }
    public void initiateResourceFile() {
        for(int x=0; x<5; x++) {
            copyFile(getClass().getResourceAsStream(FILE_PATH[x]+".jrxml"), "src"+FILE_PATH[x]+".jrxml");
            copyFile(getClass().getResourceAsStream(FILE_PATH[x]+".jasper"), "src"+FILE_PATH[x]+".jasper");
        }
        
    }
    
    public static boolean copyFile(InputStream SOURCE, String DESTINATION) {
        boolean success = false;
        try {
            PrintStream fileErr = new PrintStream("./InitiateFileErrorLog.txt");
            System.setErr(fileErr);
            System.out.println("Copying ->" + SOURCE + "\n\tto ->" + DESTINATION);
            File fl = new File(DESTINATION);
            fl.getParentFile().mkdirs();
            Files.copy(SOURCE, Paths.get(DESTINATION), StandardCopyOption.REPLACE_EXISTING);
            success = true;
        } catch (Exception ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(null, ex);
            System.setErr(System.err);
            ex.printStackTrace();
        }   
        return success;
    }
    public void login1() throws SQLException{
        String un=tuser.getText();
        String pass=tpass.getText();
        String sql= "select * username, password from login where password='"+pass+"'";
        try{
            Statement stat= conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            if(rs.next()){
                if(tpass.getText().equals(rs.getString("password"))){
                    new MenuUtama().show();
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"password dan "+"Username tidak Sesuai");
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane,"password dan username salah");
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Koneksi Database Gagal"+ex);
        }
        }
    private void tuserKeyPressed(java.awt.event.KeyEvent evt){
        int kode=evt.getKeyCode();
        if(kode==evt.VK_ENTER)
            tpass.requestFocus();   
    }
            
            
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bcan = new javax.swing.JButton();
        tuser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        blog = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tpass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan MTS. Salafiyah Syafi'iyyah");
        setResizable(false);
        setSize(new java.awt.Dimension(500, 293));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Login123.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MTS. SALAFIYAH SYAFI'IYYAH");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APLIKASI PERPUSTAKAAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 500);

        bcan.setText("CANCEL");
        bcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcanActionPerformed(evt);
            }
        });
        jPanel1.add(bcan);
        bcan.setBounds(510, 290, 90, 30);
        jPanel1.add(tuser);
        tuser.setBounds(460, 170, 150, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("PASSWORD");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 230, 90, 19);

        blog.setText("LOGIN");
        blog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogActionPerformed(evt);
            }
        });
        jPanel1.add(blog);
        blog.setBounds(350, 290, 80, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("USERNAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 180, 80, 19);

        tpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpassActionPerformed(evt);
            }
        });
        jPanel1.add(tpass);
        tpass.setBounds(460, 220, 150, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("LOGIN");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 60, 160, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(643, 476));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpassActionPerformed

    private void bcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcanActionPerformed
        // TODO add your handling code here:
        int selectedOption= JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan keluar?", "Tutup Aplikasi",
            JOptionPane.YES_NO_CANCEL_OPTION);
        if(selectedOption == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_bcanActionPerformed

    private void blogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogActionPerformed
        // TODO add your handling code here:
        try{
            Statement stat = conn.createStatement();
            String sql ="Select * from login where username = '" +tuser.getText()
            +"'and password = '"+tpass.getText()+"'";
            ResultSet rs = stat.executeQuery(sql);
            if (rs.next()){
                MenuUtama MainFrame = new MenuUtama();
                MainFrame.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null,"Success, Happy Working");
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        tuser.setText("");
        tpass.setText("");
    }//GEN-LAST:event_blogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcan;
    private javax.swing.JButton blog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables

}
