
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class Petugas extends javax.swing.JFrame {
private Statement st;
private Connection Con;
private ResultSet Rs;
private String Tanggal="";
private String Sql="";
private String host;
public String Kode_petugas,Nama_petugas,Tanggal_lahir,Tempat_lahir,Jenis_kelamin,Jabatan,Alamat,No_hp;

    /**
     * Creates new form Petugas
     */
    public Petugas() {
        initComponents();
        KoneksiPetugas();
        TampilPetugas("SELECT*FROM petugas");
        kosongkan();
        this.setTitle("Perpustakaan MTS SALFIYAH SAFI'IYAH");
    }
    private void KoneksiPetugas(){
        try {
        Class.forName("com.mysql.jdbc.Driver");    //Jika Tidak Terjadi Error
        Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpustakaan","root","");
            System.out.println("Connection Succes");
            JOptionPane.showMessageDialog(null, "Connection Succes");
        } catch (Exception e) {
            System.out.println("Connection Failed"+e);
            JOptionPane.showMessageDialog(null, "Connection failed");
        }
    }
     private void TampilPetugas(String Sql){
        DefaultTableModel  grid=new DefaultTableModel();
        grid.addColumn("No");
        grid.addColumn("Kode Petugas");
        grid.addColumn("Nama Petugas");
        grid.addColumn("Tanggal Lahir");
        grid.addColumn("Tempat Lahir");
        grid.addColumn("Jenis Kelamin");
        grid.addColumn("Jabatan");
        grid.addColumn("Alamat");
        grid.addColumn("No.Hp");
        try {
            int i=1;
            st=Con.createStatement();
            Rs=st.executeQuery("SELECT*FROM petugas");
            while (Rs.next()){
                grid.addRow(new Object[]{
                    (""+i++),Rs.getString(1),
                    Rs.getString(2),
                    Rs.getString(3),
                    Rs.getString(4),
                    Rs.getString(5),
                    Rs.getString(6),
                    Rs.getString(7),
                    Rs.getString(8)
            });
               TPETUGAS.setModel(grid);
               TPETUGAS.enable(false);
               
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Gagal Tampil: "+e);
        }
     }
     private void kosongkan (){
         TXTKODEPETUGAS.setText("");
         TXTNAMAPETUGAS.setText("");
         JTANGGAL.setDate(null);
         TXTTEMPATLAHIR.setText("");
         CBJENISKELAMIN.setSelectedItem(null);
         CBJABATAN.setSelectedItem(null);
         TXTALAMAT.setText("");
         TXTNOHP.setText("");
         TXTKODEPETUGAS.requestFocus();
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTKODEPETUGAS = new javax.swing.JTextField();
        TXTNAMAPETUGAS = new javax.swing.JTextField();
        JTANGGAL = new com.toedter.calendar.JDateChooser();
        TXTTEMPATLAHIR = new javax.swing.JTextField();
        TXTALAMAT = new javax.swing.JTextField();
        CBJENISKELAMIN = new javax.swing.JComboBox<>();
        CBJABATAN = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPETUGAS = new javax.swing.JTable();
        TXTNOHP = new javax.swing.JTextField();
        BTNSIMPAN = new javax.swing.JButton();
        BTNEDIT = new javax.swing.JButton();
        BTNBATAL = new javax.swing.JButton();
        BTNHAPUS = new javax.swing.JButton();
        BTNKELUAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("KODE PETUGAS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("NAMA PETUGAS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("TANGGAL LAHIR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("TEMPAT LAHIR");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("JENIS KELAMIN");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("JABATAN");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ALAMAT");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("NO HP");

        TXTKODEPETUGAS.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TXTKODEPETUGAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TXTKODEPETUGASKeyPressed(evt);
            }
        });

        TXTNAMAPETUGAS.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TXTNAMAPETUGAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNAMAPETUGASActionPerformed(evt);
            }
        });

        JTANGGAL.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JTANGGALPropertyChange(evt);
            }
        });

        TXTTEMPATLAHIR.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TXTTEMPATLAHIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTEMPATLAHIRActionPerformed(evt);
            }
        });

        TXTALAMAT.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        CBJENISKELAMIN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CBJENISKELAMIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Laki - Laki", "Perempuan" }));
        CBJENISKELAMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBJENISKELAMINActionPerformed(evt);
            }
        });

        CBJABATAN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CBJABATAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "ADMIN", "STAF", " ", " " }));

        TPETUGAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Petugas", "Nama Petugas", "Tanggal Lahir", "Tempat Lahir", "Jenis Kelamin", "Jabatan", "Alamat", "No Hp"
            }
        ));
        jScrollPane1.setViewportView(TPETUGAS);

        TXTNOHP.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        BTNSIMPAN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNSIMPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button simpan.png"))); // NOI18N
        BTNSIMPAN.setText("SIMPAN");
        BTNSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSIMPANActionPerformed(evt);
            }
        });

        BTNEDIT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNEDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button Edit.png"))); // NOI18N
        BTNEDIT.setText("EDIT");
        BTNEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITActionPerformed(evt);
            }
        });

        BTNBATAL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNBATAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button batal.png"))); // NOI18N
        BTNBATAL.setText("BATAL");
        BTNBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBATALActionPerformed(evt);
            }
        });

        BTNHAPUS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNHAPUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/HAPUS.png"))); // NOI18N
        BTNHAPUS.setText("HAPUS");
        BTNHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHAPUSActionPerformed(evt);
            }
        });

        BTNKELUAR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNKELUAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button Keluar.png"))); // NOI18N
        BTNKELUAR.setText("KELUAR");
        BTNKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKELUARActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Button Cetak.png"))); // NOI18N
        jButton1.setText("CETAK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTANGGAL, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(TXTKODEPETUGAS)
                    .addComponent(TXTNAMAPETUGAS)
                    .addComponent(TXTTEMPATLAHIR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TXTALAMAT)
                    .addComponent(TXTNOHP)
                    .addComponent(CBJABATAN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBJENISKELAMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNSIMPAN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNEDIT)
                .addGap(9, 9, 9)
                .addComponent(BTNBATAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNHAPUS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(BTNKELUAR)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TXTKODEPETUGAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXTNAMAPETUGAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(JTANGGAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(TXTTEMPATLAHIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBJENISKELAMIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CBJABATAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TXTALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TXTNOHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNEDIT)
                    .addComponent(BTNBATAL)
                    .addComponent(BTNHAPUS)
                    .addComponent(BTNKELUAR)
                    .addComponent(BTNSIMPAN)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/petugas1.png"))); // NOI18N
        jLabel1.setText("PETUGAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBJENISKELAMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBJENISKELAMINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBJENISKELAMINActionPerformed

    private void TXTNAMAPETUGASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNAMAPETUGASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNAMAPETUGASActionPerformed

    private void TXTTEMPATLAHIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTEMPATLAHIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTEMPATLAHIRActionPerformed

    private void BTNEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITActionPerformed
        // TODO add your handling code here:
        Kode_petugas=TXTKODEPETUGAS.getText();
        Nama_petugas=TXTNAMAPETUGAS.getText();
        Tempat_lahir=TXTTEMPATLAHIR.getText();
        Jenis_kelamin=CBJENISKELAMIN.getItemAt(CBJENISKELAMIN.getSelectedIndex());
        Jabatan=CBJABATAN.getItemAt(CBJABATAN.getSelectedIndex());
        Alamat=TXTALAMAT.getText();
        No_hp=TXTNOHP.getText();
        try { Sql="UPDATE petugas SET Nama_petugas='"+Nama_petugas+"',"
                + "Tanggal_lahir='"+Tanggal+"',"
                + "Tempat_lahir='"+Tempat_lahir+"',"
                + "Jenis_kelamin='"+Jenis_kelamin+"',"
                + "Jabatan='"+Jabatan+"',"
                + "Alamat='"+Alamat+"',"
                + "No_hp='"+No_hp+"'"
                + "WHERE Kode_petugas='"+Kode_petugas+"'";
         st=Con.createStatement();
            st.execute(Sql);
            kosongkan();
            TampilPetugas("SELECT*FROM petugas");
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Edit");
            BTNSIMPAN.show();      
        } catch (Exception e) {
             JOptionPane.showConfirmDialog(null,"Data Tidak Di Perbaharui\n"+e.getMessage());
        }                                                                           
    }//GEN-LAST:event_BTNEDITActionPerformed

    private void JTANGGALPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JTANGGALPropertyChange
        // TODO add your handling code here:
          if(JTANGGAL.getDate()!=null){
            SimpleDateFormat format =new SimpleDateFormat ("yyyy-MM-dd");
            Tanggal=format.format(JTANGGAL.getDate());
        }
    }//GEN-LAST:event_JTANGGALPropertyChange

    private void BTNSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSIMPANActionPerformed
        // TODO add your handling code here:
        Kode_petugas=TXTKODEPETUGAS.getText();
        Nama_petugas=TXTNAMAPETUGAS.getText();
        Tempat_lahir=TXTTEMPATLAHIR.getText();
        Jenis_kelamin=CBJENISKELAMIN.getItemAt(CBJENISKELAMIN.getSelectedIndex());
        Jabatan=CBJABATAN.getItemAt(CBJABATAN.getSelectedIndex());
        Alamat=TXTALAMAT.getText();
        No_hp=TXTNOHP.getText();
        try {
            Sql="INSERT INTO petugas"
                    + "(kode_petugas,Nama_petugas,Tanggal_lahir,Tempat_lahir,Jenis_kelamin,Jabatan,Alamat,No_hp)"
                    + "VALUES('"+Kode_petugas+"',"
                    + "'"+Nama_petugas+"',"
                    + "'"+Tanggal+"',"
                    + "'"+Tempat_lahir+"',"
                    + "'"+Jenis_kelamin+"',"
                    + "'"+Jabatan+"',"
                    + "'"+Alamat+"',"
                    + "'"+No_hp+"')";
            st=Con.createStatement();
            st.execute(Sql);
            kosongkan();
            TampilPetugas("SELECT*FROM petugas");
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan");
            
            BTNSIMPAN.enable(true);
                    
        } catch (Exception e) {
           JOptionPane.showConfirmDialog(null,"Data Tidak Tersimpan\n"+e.getMessage());
        }                                       
                                           
    }//GEN-LAST:event_BTNSIMPANActionPerformed

    private void BTNHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHAPUSActionPerformed
        // TODO add your handling code here:
        Kode_petugas=TXTKODEPETUGAS.getText();
        try { Sql="DELETE FROM petugas"
                + "WHERE Kode_petugas='" +Kode_petugas+ "'";
         st=Con.createStatement();
            st.execute(Sql);
            kosongkan();
            TampilPetugas("SELECT*FROM petugas");
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
           
                      
        } catch (Exception e) {
             JOptionPane.showConfirmDialog(null,"Data Tidak Di Hapus\n"+e.getMessage());
        }
               
    }//GEN-LAST:event_BTNHAPUSActionPerformed

    private void TXTKODEPETUGASKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTKODEPETUGASKeyPressed
        // TODO add your handling code here:
          Kode_petugas=TXTKODEPETUGAS.getText();
        int A = evt.getKeyCode();
        if (A==10){
            try {
                Sql="SELECT * FROM petugas WHERE Kode_petugas='"+Kode_petugas+"'";
                st=Con.createStatement();
                Rs=st.executeQuery(Sql);
                while(Rs.next()){
            TXTNAMAPETUGAS.setText(Rs.getString(2));
            JTANGGAL.setDate(Rs.getDate(3));
            TXTTEMPATLAHIR.setText(Rs.getString(4));
            CBJENISKELAMIN.setSelectedItem(Rs.getString(5));
            CBJABATAN.setSelectedItem(Rs.getString(6));
            TXTALAMAT.setText(Rs.getString(7));
            TXTNOHP.setText(Rs.getString(8));
            BTNSIMPAN.enable(false);
            BTNEDIT.enable(true);
            BTNHAPUS.enable(true);
                }
            } catch (Exception e) {
                    JOptionPane.showConfirmDialog(null, "Data Tidak Ditemukan\n"+e.getMessage());
                    TXTNAMAPETUGAS.requestFocus();
            }
        }
    }//GEN-LAST:event_TXTKODEPETUGASKeyPressed

    private void BTNBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBATALActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_BTNBATALActionPerformed

    private void BTNKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKELUARActionPerformed
        // TODO add your handling code here:
       new MenuUtama().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BTNKELUARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBATAL;
    private javax.swing.JButton BTNEDIT;
    private javax.swing.JButton BTNHAPUS;
    private javax.swing.JButton BTNKELUAR;
    private javax.swing.JButton BTNSIMPAN;
    private javax.swing.JComboBox<String> CBJABATAN;
    private javax.swing.JComboBox<String> CBJENISKELAMIN;
    private com.toedter.calendar.JDateChooser JTANGGAL;
    private javax.swing.JTable TPETUGAS;
    private javax.swing.JTextField TXTALAMAT;
    private javax.swing.JTextField TXTKODEPETUGAS;
    private javax.swing.JTextField TXTNAMAPETUGAS;
    private javax.swing.JTextField TXTNOHP;
    private javax.swing.JTextField TXTTEMPATLAHIR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
